### ISSUE TITLE
Ordering of Results in Browse

### ISSUE THREAD

**Issue by Ksepka** [NESCent/FossilCalibrations#39]
hen browsing using NCBI taxonomy, the calibrations appear in some order but I can't tell what it is - they are not in phylogenetic order, nor alphabetical, nor by ID number. Looks pretty random, especially when there are lots of results.

Proposed solution: Ideally, these would appear in some type of phylogenetic order (e.g., those assigned by us to Meazoa before those assigned to Vertebrata, before those assigned to Mammalia, before those assigned to Primates).  This may be difficult and also require the addition of more clade option on the admin end. For now, maybe we should just go alphabetical?  I assume that would be relatively easy.

**Comment by kcranston** [comment]
Are we ok to launch with the sort order as is and worry about inserting new values down the road when we have additional data? @Ksepka

**Comment by pdpolly** [comment]
Ok with me (speaking from technical end).  Mark Sutton, me, and possibly others are capable of dealing with additions or sorting.

**Comment by Ksepka** [comment]
The current order is fine for the taxon pool we have ready for launch. I
envision we will need to tweak by, for example, adding more plant sorters
but that won't be necessary for launch given the handful of plants we have
at the moment.

**Comment by hlapp** [comment]
@Ksepka - thanks for reviewing. Based on your and @pdpolly's feedback, I'll go ahead and close this.
