### ISSUE TITLE
Editing Localities

### ISSUE THREAD

**Issue by Ksepka** [NESCent/FossilCalibrations#41]
1A: I cannot seem to find a way to change data for a locality once it is entered - take for example "Xiaoxiang Resorvoir", which is used with calibrate 206 (Gnathostomata) with fossil Guiyu onerous.   I forgot to add a Formation name, but now I can't get back into that locality to do so (or at least don't know how). 

1B: Database seems to recognize a blank entry in the locality field as a locality name instead of just a blank field.  So if I leave this blank it crashes and gives this error message below. Note that ideally this is not a problem because everyone should be including a locality name, but sometimes they do not and I would thus want to leave it blank while I track it down. I have been working around this by entering "xxx" or whatever as the locality name when I don't have it.

Error message = Error in query: INSERT INTO localities SET LocalityName = '' ,Stratum = '' ,GeolTime = '384' ,Country = 'China' ,LocalityNotes = '' ,PBDBCollectionNum = ''|Duplicate entry '' for key 'LocalityName'.

1C: Related to above and more of an issue, some fossils will have the same locality name but a different stratum.  For example, I may have two birds, both from "Fossil Butte" locality, but one from "Split-Fish Layer" stratum and one from "18 Inch Layer" startum. Right now, we would have to give the locality two separate names or get an error message.

Proposed solution:  Do we need to add a "Manage Localities" option? Alternatively, should we not ask the database to search against existing localities, but let that information be a one-time entry for each calibration, like the age justification fields. Is that possible, and would the fix wipe out existing locality info (would be a bit sad to have to enter 40+ localities again)? For now I would note to Jim P. that we can use separate locality names like "Fossil Butte (1)"and "Fossil Butte (2)" to sidestep the issue.

**Comment by kcranston** [comment]
Can we get a thumbs up for this feature so that we can close the issue? @Ksepka

**Comment by Ksepka** [comment]
As stated some time ago I am satisfied with this but would like Jim and
David to give a thumbs up / thumbs down in case I missed anything in my
testing.

Look good guys?

**Comment by hlapp** [comment]
@Ksepka - I am going to close this for now. If Jim or @pdpolly can review this only later and then come to the conclusion that more needs to be done to proceed with launch, it's really easy for them (or you) to re-open the issue.

**Comment by pdpolly** [comment]
yep, I'm happy with it if Dan is.  closed.
