### ISSUE TITLE
mysqli_stmt_get_result incompatible with recommended config

### ISSUE THREAD

**Issue by dleehr** [NESCent/FossilCalibrations#53]
Not sure how to phrase this as an issue, but it complicates the installation issues #13 and conflicts with the recommended config in the wiki installation documentation.

The install doc recommends PHP 5.3. Recent changes to address SQL injection #17 have added calls to  `mysqli_stmt_get_result`. This function [exists in PHP 5.3](http://php.net/manual/en/mysqli-stmt.get-result.php) but only with the MySQL native driver ([mysqlnd](http://dev.mysql.com/downloads/connector/php-mysqlnd/)), which is not the default in 5.3.

mysqlnd became the default in PHP 5.4 (CentOS 7), so the official CentOS 5 and 6 packages aren't compatible with this change. There are third-party packages to get PHP 5.3 with mysqlnd, but I'm hesitant to start installing them.

Is there a recommendation on where to get a necessary version of php - I saw previous references to XAMPP but it's not mentioned in the installation documentation anymore.

**Comment by jimallman** [comment]
The latest code (as of 28d6fb44cc4564148891f6c368990b1dcf0887fd) should no longer require mysqlnd.

**Comment by dleehr** [comment]
Also live on NESCent-hosted server.
