### ISSUE TITLE
Wikipedia / NCBI / Animal Diversity Web

### ISSUE THREAD

**Issue by Ksepka** [NESCent/FossilCalibrations#65]
For dicussion - we previously had these links active for all calibrations, but encountered the issue of nodes that don't match names (e.g. Stem Sphenisciformes" would trigger a broken link rather than point to Sphenisciformes on these sites). I think we have largely bypassed that issue with the new system of using the common name and then the drop down menu for Stem/Crown.  Can we try turning these links back on again? I'd be interested in seeing if they mostly work fine now, and then deciding as a group wether we should leave them on or off in the flinch version.

**Comment by dleehr** [comment]
Pushed latest master branch to fossilcalibrations.org, so this is live there too.
