### ISSUE TITLE
Need to change copyright statement in footer

### ISSUE THREAD

**Issue by kcranston** [NESCent/FossilCalibrations#66]
The footer of the page states "© 2013, Sponsored by: Coquina Press, NESCent ". The footer should be clear that all data is released under a CC0 waiver. Suggestion (using wording from Dryad):
 
"To the extent possible under law, the authors have waived all copyright and related or neighboring rights to the data in the Fossil Calibrations database. <CC0 image and link to CC0 page>"

@hlapp - Comments? I am including this as a requirement in the hand-off letter.

**Comment by kcranston** [comment]
Reopening, because the footer still contains the copyright symbol. It should indicate that all data is CC0, with a link to https://creativecommons.org/publicdomain/zero/1.0/. (Note that CC0 is a waiver of copyright, so including a copyright symbol is in conflict with the text).

**Comment by jimallman** [comment]
Hm, I neglected to specify and link to **CC0**, sorry about that. 

But I believe copyright would still apply to the source code, About pages, etc. The [BSD license](https://github.com/NESCent/FossilCalibrations/blob/master/LICENSE.txt) assumes a copyright holder who grants permissions. Maybe we can clarify this distinction, something like this:

> Sponsored by [Coquina Press](http://palaeo-electronica.org/owner.htm) and [NESCent](http://nescent.org/). &bull; All data is released under a [CC0 waiver](https://creativecommons.org/publicdomain/zero/1.0/). To the extent possible under law, the authors have waived all copyright and related or neighboring rights to the data in the Fossil Calibrations database. &bull; Full [source code](https://github.com/NESCent/FossilCalibrations) for this website (&copy; 2013-2014, National Evolutionary Synthesis Center) is available under the [BSD (2-clause) license](https://github.com/NESCent/FossilCalibrations/blob/master/LICENSE.txt).

**Comment by jimallman** [comment]
Based on #70, I'll bump the date range for the source-code copyright as follows:
> (© 2013-2015, National Evolutionary Synthesis Center)
