### ISSUE TITLE
Failed search terms carried over.

### ISSUE THREAD

**Issue by Ksepka** [NESCent/FossilCalibrations#69]
If a user searches for a term that yields no results from the front page (fossilcalibrations.org) and there are no results, the search term gets carried over. 

Example - search "turtle" and there are no results.  The user may then add a clade filter "Reptilia" and update, but still get no results because "turtle" is still left in the top box.  If "turtle" is deleted, the "Reptilia" clade feature yields good results.

I understand this should be evident to a smart user, but first timers may get confused and think there are no Reptilia at all because they either don't understand that "turtle" is ruining the search or they simply don't notice it was carried over.

Proposed solution - can we have that top field (left of "update" button) not carry over the previous search term?

**Comment by dleehr** [comment]
Pushed latest master branch to fossilcalibrations.org, so this is live there too.
