### ISSUE TITLE
Cosmetic Changes

### ISSUE THREAD

**Issue by Ksepka** [NESCent/FossilCalibrations#70]
This is a list of primarily wording changes/edits to prepare for launch:

MAIN PAGE (http://www.fossilcalibrations.org)

1. Please delete the "Welcome to the new server!" text block at upper right.

2. The links in the lower right text block do not work (they refresh the current page):
"The Fossil Calibration Database is a curated collection of well-justified calibrations, including many published in the journal Palaeontologia Electronica. We also promote best practices for justifying fossil calibrations and citing calibrations properly."
[Palaeontologia Electronica] should point here:  http://palaeo-electronica.org
[justifying fossil calibrations] should point here: http://sysbio.oxfordjournals.org/content/61/2/346.short
[citing calibrations] should just be plain text (not a link).

3. Footer: I assume the copyright date should be 2015 though maybe I am wrong (e.g. does this date reflect the release or the development date?).

ABOUT US page (http://www.fossilcalibrations.org/about.php):

1. Photo 1 caption:  Two names missing ( Krister Smith & Johannes Müller), please add as listed below:

Jason Head, Michael Benton, Tyler Calway, Philip Donoghue, Ken Angielczyk, Krister Smith, James Tarver, Jenny Greenwood, Nathan Smith, Peter Makovicky, James Parham (leader). Chris Bell, Jun Inoue; (Back row, left to right): Randall Irmis, Marcel van Tuinen, Christy Hipsley,  Johannes Müller, Ziheng Yang, Daniel Ksepka, Walter Joyce, Patricia Holroyd, Jessica Theodor, Rachel Warnock, Louis Jacobs. 

2. Photo 2 caption: Please change "Maria Gandolfo" to "Maria Gandolfo Nixon".

3. Photo 3 caption: Please change "Rachel Ware" to "Jessica Ware". Please add "Not shown: Adam Smith, Marcel van Tuinen."

FAQ (http://www.fossilcalibrations.org/faq.php)

1. The question "How do I download data?" states "From any page of search results, click the Download button to download a list of results as JSON or text." What is the status of this button?  We should remove this text if it is not going to be ready for launch.

2. In "How should I cite calibrations from the database?, please eliminate the reference to the Systematic Biology paper for the time being, as it will not be published when we launch. 

Delete:
"The preferred citation for the database itself is listed below, but should not be used in place of citing the original papers when using specific calibrations.
[Title of Systematic Biology Paper]

**Comment by jimallman** [comment]
> The question "How do I download data?" states "From any page of search results, click the Download button to download a list of results as JSON or text." What is the status of this button? We should remove this text if it is not going to be ready for launch.

@dleehr, Can the current API support this feature? Or should I remove this mention from the FAQ?

**Comment by dleehr** [comment]
For the most part, the API can support this. The API parameters match pretty closely to what the PHP web interface does, and it can return JSON or CSV data.

The [fcdb-api](http://github.com/NESCent/fcdb-api/) is a Node.js application. It's not installed on the servers and may not be final. Officially, we're awaiting feedback in #73.

**Comment by jimallman** [comment]
Thanks! I'll comment this out in the FAQ for now. But we should be able to circle back and add this quickly once the API dust has settled.

**Comment by jimallman** [comment]
@Ksepka , note the the copyright block (in the site footer) will be changing to more accurately reflect our use of CC0. See #66 for details.

**Comment by jimallman** [comment]
> Please delete the "Welcome to the new server!" text block at upper right.

@Ksepka, note that this announcement box is editable by any logged-in admin. Just click the (temporary) link with text "edit this announcement", or choose **Edit Site Announcement** from the Admin Dashboard page, or just [jump directly to the editor](https://fossilcalibrations.org/protected/edit_site_announcement.php).

Note that you can clear just the title, or the entire announcement. In the latter case, this box will disappear from the right sidebar until a new announcement is entered.

**Comment by jimallman** [comment]
Changes to About page done in commit 66f7af75c7fff398ef472acd08a5350bc9af23b7

**Comment by jimallman** [comment]
@Ksepka, @dleehr : Note that the FAQ entry **How do I download data?** describes Download buttons on both the search results page and the single-calibration display page. I'm hiding both of these tips, since neither button presently exists. Instead, I'll describe this kind of functionality (along with the API) as "coming soon".

**Comment by jimallman** [comment]
Apart from the admin-editable message box, these changes are all in place and available for review on [my FCD test server](http://fossils.ibang.com/). Once @dleehr has deployed these changes on the production site, please mark this issue as complete.

**Comment by Ksepka** [comment]
Thanks Jim. I removed the announcement box following your instructions and
it worked fine, sorry for not spotting that option earlier. Standing by for
the next deploy.

**Comment by dleehr** [comment]
Pushed this code to the production site. Also updated the API link in the FAQ
