### ISSUE TITLE
SSL cert for fossilcalibrations.org

### ISSUE THREAD

**Issue by hlapp** [NESCent/FossilCalibrations#76]
The fossilcalibrations.org server has now moved to a PalAss server. I assume that as a result of that, the SSL address fails to domain-validate and browsers show a big scary warning. I assume this means that the SSL cert needs to be re-issued and installed on the PalAss webserver.

@dleehr and @jimallman - it seems that the HTTP URL doesn't redirect to HTTPS. Is this intentional, or on oversight from the move to PalAss, and if the former, are there redirect rules in place somewhere that ensure that login and other pages use HTTPS?

**Comment by dleehr** [comment]
The [login](https://github.com/NESCent/FossilCalibrations/blob/28d6fb44cc4564148891f6c368990b1dcf0887fd/login.php#L6) page requires/redirects to https. There's also an [.htaccess](https://github.com/NESCent/FossilCalibrations/blob/28d6fb44cc4564148891f6c368990b1dcf0887fd/protected/.htaccess.EXAMPLE) file for the /protected directory that forces https, but I don't know if that's configured on the PalAss host

**Comment by kcranston** [comment]
I am not getting an SSL warning on either firefox or chrome.

**Comment by dleehr** [comment]
No it's giving a self-signed certificate
![fcd-self-signed](https://cloud.githubusercontent.com/assets/2752599/6231724/77a03f8a-b695-11e4-8cb8-8a25e00c464f.png)

**Comment by hlapp** [comment]
@dleehr yes, I was able to see that too now. 

@kcranston I'll have an email out in a moment.

**Comment by jimallman** [comment]
We've previously raised the question of whether or not a [self-signed cert might be OK](https://github.com/NESCent/FossilCalibrations/wiki/Installation) for this site, since only the admin users (a small group) will be bumped to HTTPS. I don't know if a final decision was ever reached.

**Comment by dleehr** [comment]
Also it does not appear that http://fossilcalibrations.org/protected enforces https

**Comment by hlapp** [comment]
> We've previously raised the question of whether or not a self-signed cert might be OK for this site, since only the admin users (a small group) will be bumped to HTTPS. I don't know if a final decision was ever reached.

It was. Self-signed certs are poor practice, and require only a nominal expense to rectify.

**Comment by jimallman** [comment]
Ah, I forgot that this cert has already been secured. 

Based on a quick look at the cert on https://152.3.101.137/, it seems to support both **fossilcalibrations.org** and **www.fossilcalibrations.org**. For SEO purposes, it's probably best to nudge to one or the other in our apache configuration. (This is not discussed in the Installation wiki page.)

**Comment by hlapp** [comment]
Cert is now re-issued and installed.
