### ISSUE TITLE
Still in the works?

### ISSUE THREAD

**Issue by sckott** [NESCent/FossilCalibrations#80]
What stage is this at now?  Holding pattern?

**Comment by jimallman** [comment]
The [Fossil Calibrations website](http://www.fossilcalibrations.org/) has been up for some time now. Are you asking about a specific feature?

**Comment by hlapp** [comment]
The [API](https://github.com/NESCent/FossilCalibrations/wiki/Application-Programming-Interface-(API)) is [live as well since July 2015](https://twitter.com/hlapp/status/616618750243155968), although I notice that the URLs in the [Apiary docs](http://docs.fossilcalibrations.apiary.io/#) seem truncated. I'll post an issue to the tracker about that.

The code for the website and API are not currently under active development, to the extent I know. (cc @marksutton and @pdpolly in case they have plans and/or are actively maintaining the codebase.)

**Comment by marksutton** [comment]
I'm certainly neither doing anything to it, nor planning to do so!

M.



On 30/11/2015 15:55, Hilmar Lapp wrote:
>
> The API 
> <https://github.com/NESCent/FossilCalibrations/wiki/Application-Programming-Interface-%28API%29> 
> is live as well since July 2015 
> <https://twitter.com/hlapp/status/616618750243155968>, although I 
> notice that the URLs in the Apiary docs 
> <http://docs.fossilcalibrations.apiary.io/#> seem truncated. I'll post 
> an issue to the tracker about that.
>
> The code for the website and API are not currently under active 
> development, to the extent I know. (cc @marksutton 
> <https://github.com/marksutton> and @pdpolly 
> <https://github.com/pdpolly> in case they have plans and/or are 
> actively maintaining the codebase.)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NESCent/FossilCalibrations/issues/80#issuecomment-160669779>.
>

-- 

Dr Mark Sutton, Senior Lecturer, Palaeontology
Department of Earth Science & Engineering
South Kensington Campus, Imperial College London, SW7 2AZ
Tel: (+44) 20 759 47487
Mob: (+44) 7904 530407

**Comment by pdpolly** [comment]
As far as I know all current API work was finished under NESCent with no more planned for the immediate future.  External support will be sought if new developments are needed.

Best wishes,
David

**Comment by sckott** [comment]
Sorry, should have added more details. I gave some input a while back this year on the API design, so I was curious if it had been released. Sorry I missed the announcement. 

> The code for the website and API are not currently under active development,

> As far as I know all current API work was finished under NESCent with no more planned for the immediate future.  External support will be sought if new developments are needed.

Does this mean bugs/feature requests will be put off until more $$ support is found?

**Comment by hlapp** [comment]
> Does this mean bugs/feature requests will be put off until more $$ support is found?

If by this you mean to ask, is there someone who gets paid to address bug/feature requests you post, the answer is no. If you mean to ask, can people willing to contribute submit pull requests that will get looked at and merged, the answer is in principle yes. (And I'm assuming @marksutton would be willing to deploy code updates from the repository?)

**Comment by marksutton** [comment]
On 30/11/2015 16:21, Hilmar Lapp wrote:
>
>     Does this mean bugs/feature requests will be put off until more $$
>     support is found?
>
> If by this you mean to ask, is there someone who gets paid to address 
> bug/feature requests you post, the answer is no. If you mean to ask, 
> can people willing to contribute submit pull requests that will get 
> looked at and merged, the answer is in principle yes. (And I'm 
> assuming @marksutton <https://github.com/marksutton> would be willing 
> to deploy code updates from the repository?)
>
Yes, as long as someone tells me when to do so!

M.


> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NESCent/FossilCalibrations/issues/80#issuecomment-160677385>.
>

-- 

Dr Mark Sutton, Senior Lecturer, Palaeontology
Department of Earth Science & Engineering
South Kensington Campus, Imperial College London, SW7 2AZ
Tel: (+44) 20 759 47487
Mob: (+44) 7904 530407

**Comment by sckott** [comment]
Thanks, just curious if I should report things if found

**Comment by hlapp** [comment]
> Thanks, just curious if I should report things if found

Yes please :smile:

**Comment by pdpolly** [comment]
We're committed to maintaining the existing system, so malfunction reports are welcome.   Suggestions for future developments are also welcome.  Development suggestions will be most helpful if sent directly to James Parham (jfparham@gmail.com) and Dan Ksepka (ksepka@gmail.com), the editors of the Fossil Calibration Database who will be the ones to initiate expansions of the FCD.

**Comment by sckott** [comment]
thanks
